/* Generated on 2019-09-07 11:43:50.028192
* This file contains all of the constants that are
* being used on the CAN bus.
*
* Each message has an ID with specified sensors that
* lie on each message from bytes *_START_BYTE to
* *_END_BYTE.
*/

#ifndef CANID_H
#define CANID_H
#define WHEEL_SPEED_FRONT_CAN_ID 0x700
#define WHEEL_SPEED_FRONT_L_START_BIT 0
#define WHEEL_SPEED_FRONT_L_END_BIT 31
#define WHEEL_SPEED_FRONT_R_START_BIT 32
#define WHEEL_SPEED_FRONT_R_END_BIT 63

#define WHEEL_SPEED_REAR_CAN_ID 0x701
#define WHEEL_SPEED_REAR_L_START_BIT 0
#define WHEEL_SPEED_REAR_L_END_BIT 31
#define WHEEL_SPEED_REAR_R_START_BIT 32
#define WHEEL_SPEED_REAR_R_END_BIT 63

#define TIRE_TEMP_FRONT_CAN_ID 0x710
#define TIRE_TEMP_FRONT_R_START_BIT 0
#define TIRE_TEMP_FRONT_R_END_BIT 15
#define TIRE_TEMP_FRONT_L_START_BIT 16
#define TIRE_TEMP_FRONT_L_END_BIT 31

#define TIRE_TEMP_REAR_CAN_ID 0x711
#define TIRE_TEMP_REAR_R_START_BIT 0
#define TIRE_TEMP_REAR_R_END_BIT 15
#define TIRE_TEMP_REAR_L_START_BIT 16
#define TIRE_TEMP_REAR_L_END_BIT 31

#define COOLANT_CAN_ID 0x720
#define COOLANT_MOTOR_START_BIT 0
#define COOLANT_MOTOR_END_BIT 15
#define COOLANT_RAD_START_BIT 16
#define COOLANT_RAD_END_BIT 31
#define COOLANT_MC_START_BIT 32
#define COOLANT_MC_END_BIT 47

#define COOLANT_CAN_ID 0x721
#define COOLANT_FLOW_START_BIT 0
#define COOLANT_FLOW_END_BIT 31

#define SHOCK_POT_FRONT_CAN_ID 0x730
#define SHOCK_POT_FRONT_L_START_BIT 0
#define SHOCK_POT_FRONT_L_END_BIT 15
#define SHOCK_POT_FRONT_R_START_BIT 16
#define SHOCK_POT_FRONT_R_END_BIT 31

#define SHOCK_POT_REAR_CAN_ID 0x731
#define SHOCK_POT_REAR_R_START_BIT 0
#define SHOCK_POT_REAR_R_END_BIT 15
#define SHOCK_POT_REAR_L_START_BIT 16
#define SHOCK_POT_REAR_L_END_BIT 31

#define DROP_LINK_CAN_ID 0x740
#define DROP_LINK_LEFT_START_BIT 0
#define DROP_LINK_LEFT_END_BIT 15
#define DROP_LINK_RIGHT_START_BIT 16
#define DROP_LINK_RIGHT_END_BIT 31

#define PUSHROD_FRONT_CAN_ID 0x750
#define PUSHROD_FRONT_R_START_BIT 0
#define PUSHROD_FRONT_R_END_BIT 15
#define STEER_ROD_FRONT_R_START_BIT 16
#define STEER_ROD_FRONT_R_END_BIT 31
#define PUSHROD_FRONT_L_START_BIT 32
#define PUSHROD_FRONT_L_END_BIT 47
#define STEER_ROD_FRONT_L_START_BIT 48
#define STEER_ROD_FRONT_L_END_BIT 63

#define PUSHROD_REAR_CAN_ID 0x760
#define PUSHROD_REAR_R_START_BIT 0
#define PUSHROD_REAR_R_END_BIT 15
#define TIEROD_REAR_R_START_BIT 16
#define TIEROD_REAR_R_END_BIT 31
#define PUSHROD_REAR_L_START_BIT 32
#define PUSHROD_REAR_L_END_BIT 47
#define TIEROD_REAR_L_START_BIT 48
#define TIEROD_REAR_L_END_BIT 63

#define LCA_FRONT_CAN_ID 0x770
#define LCA_FRONT_LF_START_BIT 0
#define LCA_FRONT_LF_END_BIT 15
#define LCA_FRONT_LB_START_BIT 16
#define LCA_FRONT_LB_END_BIT 31
#define LCA_FRONT_RF_START_BIT 32
#define LCA_FRONT_RF_END_BIT 47
#define LCA_FRONT_RB_START_BIT 48
#define LCA_FRONT_RB_END_BIT 63

#define LCA_REAR_CAN_ID 0x780
#define LCA_REAR_LF_START_BIT 0
#define LCA_REAR_LF_END_BIT 15
#define LCA_REAR_LB_START_BIT 16
#define LCA_REAR_LB_END_BIT 31
#define LCA_REAR_RF_START_BIT 32
#define LCA_REAR_RF_END_BIT 47
#define LCA_REAR_RB_START_BIT 48
#define LCA_REAR_RB_END_BIT 63

#define UCA_FRONT_CAN_ID 0x790
#define UCA_FRONT_LF_START_BIT 0
#define UCA_FRONT_LF_END_BIT 15
#define UCA_FRONT_LB_START_BIT 16
#define UCA_FRONT_LB_END_BIT 31
#define UCA_FRONT_RF_START_BIT 32
#define UCA_FRONT_RF_END_BIT 47
#define UCA_FRONT_RB_START_BIT 48
#define UCA_FRONT_RB_END_BIT 63

#define UCA_REAR_CAN_ID 0x7a0
#define UCA_REAR_LF_START_BIT 0
#define UCA_REAR_LF_END_BIT 15
#define UCA_REAR_LB_START_BIT 16
#define UCA_REAR_LB_END_BIT 31
#define UCA_REAR_RF_START_BIT 32
#define UCA_REAR_RF_END_BIT 47
#define UCA_REAR_RB_START_BIT 48
#define UCA_REAR_RB_END_BIT 63

#define FRONT_TORSIONAL_CAN_ID 0x7b0
#define FRONT_TORSIONAL_ARB_START_BIT 0
#define FRONT_TORSIONAL_ARB_END_BIT 15

#define REAR_TORSIONAL_CAN_ID 0x7b1
#define REAR_TORSIONAL_ARB_START_BIT 0
#define REAR_TORSIONAL_ARB_END_BIT 15

#define STEERING_CAN_ID 0x7c0
#define STEERING_TORSION_START_BIT 0
#define STEERING_TORSION_END_BIT 15
#define STEERING_ANGLE_START_BIT 16
#define STEERING_ANGLE_END_BIT 31

#define X_CAN_ID 0x7d0
#define X_AXIS [15:8]_START_BIT 8
#define X_AXIS [15:8]_END_BIT 15
#define X_AXIS [7:0]_START_BIT 16
#define X_AXIS [7:0]_END_BIT 23
#define Y_AXIS [15:8] _START_BIT 24
#define Y_AXIS [15:8] _END_BIT 31
#define Y_AXIS [7:0]_START_BIT 32
#define Y_AXIS [7:0]_END_BIT 39
#define Z_AXIS [15:8] _START_BIT 40
#define Z_AXIS [15:8] _END_BIT 47
#define Z_AXIS [7:0] _START_BIT 48
#define Z_AXIS [7:0] _END_BIT 55

#define L_WHEEL_SPD_CAN_ID 0x7f0
#define L_WHEEL_SPD_ERROR_START_BIT 0
#define L_WHEEL_SPD_ERROR_END_BIT 7
#define R_WHEEL_SPEED_ERROR_START_BIT 8
#define R_WHEEL_SPEED_ERROR_END_BIT 15
#define MAX11614_ERROR_START_BIT 16
#define MAX11614_ERROR_END_BIT 23
#define MAX11616_ERROR_START_BIT 24
#define MAX11616_ERROR_END_BIT 31

#define L_WHEEL_SPD_CAN_ID 0x7f1
#define L_WHEEL_SPD_ERROR_START_BIT 0
#define L_WHEEL_SPD_ERROR_END_BIT 7
#define R_WHEEL_SPEED_ERROR_START_BIT 8
#define R_WHEEL_SPEED_ERROR_END_BIT 15
#define MAX11614_ERROR_START_BIT 16
#define MAX11614_ERROR_END_BIT 23
#define MAX11616_ERROR_START_BIT 24
#define MAX11616_ERROR_END_BIT 31
#define COOL_SPD_ERROR_START_BIT 32
#define COOL_SPD_ERROR_END_BIT 39

#define FLAG_SPEED_CAN_MASK_BIT 7
#define FLAG_UCA_CAN_MASK _BIT 6
#define FLAG_LCA_CAN_MASK   _BIT 5
#define FLAG_SHOCK_CAN_MASK  _BIT 4
#define FLAG_ARB_TORS_CAN_MASK _BIT 3
#define FLAG_PUSH_ROD_CAN_MASK _BIT 2
#define FLAG_COOLANT_CAN_MASK  _BIT 1
#define FLAG_DROP_LINK_CAN_MASK_BIT 0
#endif /* CANID_H */