/* Generated on 2019-02-11 22:18:49.360491
* This file contains all of the constants that are
* being used on the CAN bus.
*
* Each message has an ID with specified sensors that
* lie on each message from bytes *_START_BYTE to
* *_END_BYTE.
*/

#ifndef CANID_H
#define CANID_H
#define  WHEEL_SPEED_FRONT_CAN_ID 0x700
#define  WHEEL_SPEED_FRONT_L_START_BYTE  0
#define  WHEEL_SPEED_FRONT_L_END_BYTE  1
#define  WHEEL_SPEED_FRONT_R_START_BYTE  2
#define  WHEEL_SPEED_FRONT_R_END_BYTE  3

#define  WHEEL_SPEED_REAR_CAN_ID 0x701
#define  WHEEL_SPEED_REAR_L_START_BYTE  0
#define  WHEEL_SPEED_REAR_L_END_BYTE  1
#define  WHEEL_SPEED_REAR_R_START_BYTE  2
#define  WHEEL_SPEED_REAR_R_END_BYTE  3

#define  TIRE_TEMP_FRONT_CAN_ID 0x710
#define  TIRE_TEMP_FRONT_L_START_BYTE  0
#define  TIRE_TEMP_FRONT_L_END_BYTE  1
#define  TIRE_TEMP_FRONT_R_START_BYTE  2
#define  TIRE_TEMP_FRONT_R_END_BYTE  3

#define  TIRE_TEMP_REAR_CAN_ID 0x711
#define  TIRE_TEMP_REAR_L_START_BYTE  0
#define  TIRE_TEMP_REAR_L_END_BYTE  1
#define  TIRE_TEMP_REAR_R_START_BYTE  2
#define  TIRE_TEMP_REAR_R_END_BYTE  3

#define  COOLANT_CAN_ID 0x720
#define  COOLANT_RAD_START_BYTE  0
#define  COOLANT_RAD_END_BYTE  1
#define  COOLANT_MOTOR_START_BYTE  2
#define  COOLANT_MOTOR_END_BYTE  3
#define  COOLANT_MC_START_BYTE  4
#define  COOLANT_MC_END_BYTE  5
#define  COOLANT_FLOW_START_BYTE  6
#define  COOLANT_FLOW_END_BYTE  7

#define  SHOCK_POT_FRONT_CAN_ID 0x730
#define  SHOCK_POT_FRONT_L_START_BYTE  0
#define  SHOCK_POT_FRONT_L_END_BYTE  1
#define  SHOCK_POT_FRONT_R_START_BYTE  2
#define  SHOCK_POT_FRONT_R_END_BYTE  3

#define  SHOCK_POT_REAR_CAN_ID 0x731
#define  SHOCK_POT_REAR_L_START_BYTE  0
#define  SHOCK_POT_REAR_L_END_BYTE  1
#define  SHOCK_POT_REAR_R_START_BYTE  2
#define  SHOCK_POT_REAR_R_END_BYTE  3

#define  DROP_LINK_CAN_ID 0x740
#define  DROP_LINK_LEFT_START_BYTE  0
#define  DROP_LINK_LEFT_END_BYTE  1
#define  DROP_LINK_RIGHT_START_BYTE  2
#define  DROP_LINK_RIGHT_END_BYTE  3

#define  STEER_ROD_FRONT_CAN_ID 0x750
#define  STEER_ROD_FRONT_L_START_BYTE  0
#define  STEER_ROD_FRONT_L_END_BYTE  1
#define  STEER_ROD_FRONT_R_START_BYTE  2
#define  STEER_ROD_FRONT_R_END_BYTE  3
#define  PUSHROD_FRONT_L_START_BYTE  4
#define  PUSHROD_FRONT_L_END_BYTE  5
#define  PUSHROD_FRONT_R_START_BYTE  6
#define  PUSHROD_FRONT_R_END_BYTE  7

#define  TIEROD_REAR_CAN_ID 0x760
#define  TIEROD_REAR_L_START_BYTE  0
#define  TIEROD_REAR_L_END_BYTE  1
#define  TIEROD_REAR_R_START_BYTE  2
#define  TIEROD_REAR_R_END_BYTE  3
#define  PUSHROD_REAR_L_START_BYTE  4
#define  PUSHROD_REAR_L_END_BYTE  5
#define  PUSHROD_REAR_R_START_BYTE  6
#define  PUSHROD_REAR_R_END_BYTE  7

#define  LCA_FRONT_CAN_ID 0x770
#define  LCA_FRONT_LF_START_BYTE  0
#define  LCA_FRONT_LF_END_BYTE  1
#define  LCA_FRONT_LB_START_BYTE  2
#define  LCA_FRONT_LB_END_BYTE  3
#define  LCA_FRONT_RF_START_BYTE  4
#define  LCA_FRONT_RF_END_BYTE  5
#define  LCA_FRONT_RB_START_BYTE  6
#define  LCA_FRONT_RB_END_BYTE  7

#define  LCA_REAR_CAN_ID 0x780
#define  LCA_REAR_LF_START_BYTE  0
#define  LCA_REAR_LF_END_BYTE  1
#define  LCA_REAR_LB_START_BYTE  2
#define  LCA_REAR_LB_END_BYTE  3
#define  LCA_REAR_RF_START_BYTE  4
#define  LCA_REAR_RF_END_BYTE  5
#define  LCA_REAR_RB_START_BYTE  6
#define  LCA_REAR_RB_END_BYTE  7

#define  UCA_FRONT_CAN_ID 0x790
#define  UCA_FRONT_LF_START_BYTE  0
#define  UCA_FRONT_LF_END_BYTE  1
#define  UCA_FRONT_LB_START_BYTE  2
#define  UCA_FRONT_LB_END_BYTE  3
#define  UCA_FRONT_RF_START_BYTE  4
#define  UCA_FRONT_RF_END_BYTE  5
#define  UCA_FRONT_RB_START_BYTE  6
#define  UCA_FRONT_RB_END_BYTE  7

#define  UCA_REAR_CAN_ID 0x7A0
#define  UCA_REAR_LF_START_BYTE  0
#define  UCA_REAR_LF_END_BYTE  1
#define  UCA_REAR_RF_START_BYTE  2
#define  UCA_REAR_RF_END_BYTE  3
#define  UCA_REAR_LB_START_BYTE  4
#define  UCA_REAR_LB_END_BYTE  5
#define  UCA_REAR_RB_START_BYTE  6
#define  UCA_REAR_RB_END_BYTE  7

#define  FRONT_TORSIONAL_CAN_ID 0x7B0
#define  FRONT_TORSIONAL_ARB_START_BYTE  0
#define  FRONT_TORSIONAL_ARB_END_BYTE  1

#define  REAR_TORSIONAL_CAN_ID 0x7B1
#define  REAR_TORSIONAL_ARB_START_BYTE  0
#define  REAR_TORSIONAL_ARB_END_BYTE  1

#define  STEERING_CAN_ID 0x7C0
#define  STEERING_ANGLE_START_BYTE  0
#define  STEERING_ANGLE_END_BYTE  1
#define  STEERING_TORSION_START_BYTE  2
#define  STEERING_TORSION_END_BYTE  3

#define  IMU_CAN_ID 0x7D0
#define  IMU_TYPE_START_BYTE  0
#define  IMU_TYPE_END_BYTE  0
#define  IMU_DATA_START_BYTE  1
#define  IMU_DATA_END_BYTE  2
#define  IMU_TIME_START_BYTE  3
#define  IMU_TIME_END_BYTE  5
#endif /* CANID_H */